### ISSUE TITLE
Problem building environment with hvplot and bokeh=1

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/hvplot-feedstock#2]
I tried creating an environment using:
```
name: root
channels:
  - conda-forge
dependencies:
  - hvplot
  - bokeh=1
``` 
and got:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - bokeh=1
  - hvplot
```
Yet, things seem okay from `conda info`:
```
jovyan@jupyter-rsignell-2dusgs:~$ conda info hvplot

hvplot 0.2.1 py_1
-----------------
file name   : hvplot-0.2.1-py_1.tar.bz2
name        : hvplot
version     : 0.2.1
build string: py_1
build number: 1
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 1.2 MB
arch        : None
constrains  : ()
license     : BSD-3-Clause
license_family: BSD
md5         : 6980a49bca58aff29e8f111cf0c83005
noarch      : python
platform    : None
subdir      : noarch
timestamp   : 1535043306760
url         : https://conda.anaconda.org/conda-forge/noarch/hvplot-0.2.1-py_1.tar.bz2
dependencies:
    bokeh >=0.12.15
    holoviews >=1.10.5
    pandas
    python
```
```
jovyan@jupyter-rsignell-2dusgs:~$ conda info bokeh=1

bokeh 1.0.0 py36_1000
---------------------
file name   : bokeh-1.0.0-py36_1000.tar.bz2
name        : bokeh
version     : 1.0.0
build string: py36_1000
build number: 1000
channel     : https://conda.anaconda.org/conda-forge/linux-64
size        : 5.3 MB
arch        : x86_64
constrains  : ()
license     : BSD 3-Clause
license_family: BSD
md5         : f8a9b7950acf997dd83b7c079f41fd1c
platform    : linux
subdir      : linux-64
timestamp   : 1540402537815
url         : https://conda.anaconda.org/conda-forge/linux-64/bokeh-1.0.0-py36_1000.tar.bz2
dependencies:
    jinja2 >=2.7
    numpy >=1.7.1
    packaging >=16.8
    pillow >=4.0
    python >=3.6,<3.7.0a0
    python-dateutil >=2.1
    pyyaml >=3.10
    six >=1.5.2
    tornado >=4.3
```

**Comment by rsignell-usgs** [comment]
Normally I would just bug @ocefpaf, but he is gone for long well-deserved weekend...

**Comment by philippjfr** [comment]
We'll be releasing holoviews 1.10.8 asap and I'll follow up with hvplot shortly after.

**Comment by ocefpaf** [comment]
@rsignell-usgs and @philippjfr the problem is this pin on holoviews:

https://github.com/conda-forge/holoviews-feedstock/blob/master/recipe/meta.yaml#L28

which does not allow for its installation with `bokeh >0.13.0`.

I'm not familiar with the code base to know if we can remove that.

**Comment by ocefpaf** [comment]
Actually, the source says `bokeh>=0.12.15`, so I guess the feedstock is outdated. Fixing that now!

**Comment by philippjfr** [comment]
>Actually, the source says bokeh>=0.12.15, so I guess the feedstock is outdated. Fixing that now!

We're releasing holoviews 1.10.8 in the next hour. The current release is not compatible with bokeh 1.0 but the new one will be.

**Comment by ocefpaf** [comment]
> We're releasing holoviews 1.10.8 in the next hour. The current release is not compatible with bokeh 1.0 but the new one will be.

OK. I'll wait for that then. Thanks @philippjfr!

**Comment by philippjfr** [comment]
HoloViews 1.10.8 is now released on the pyviz channel:

https://anaconda.org/pyviz/holoviews/files

**Comment by rsignell-usgs** [comment]
PyPi?

**Comment by philippjfr** [comment]
Uploaded a few seconds ago:

https://pypi.org/project/holoviews/#files

**Comment by ocefpaf** [comment]
Thanks @philippjfr!
