### ISSUE TITLE
Remove `-k 'not test_explorer_geo_revise_kind'` for the next release

### ISSUE THREAD

**Issue by maximlt** [conda-forge/hvplot-feedstock#31]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Remove `-k 'not test_explorer_geo_revise_kind'` for the next release: https://github.com/conda-forge/hvplot-feedstock/pull/30/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR43

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by ocefpaf** [comment]
We usually forget these changes when a release is out and, if you don't bump the build number, no new package will be created. TL;DR, if you want to implement that change now, just don't bump the build number.

**Comment by maximlt** [comment]
Done in https://github.com/conda-forge/hvplot-feedstock/pull/32
